---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: shrutivilankar/concoursedocker:0.0.1-SNAPSHOT
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/unit.sh
